### PR TITLE
#6562 update HERON website

### PR DESCRIPTION
**Pull request by anuforok**
- At the top of the page, remove the list of data sources.
- Replace all references to heron-admin@kumc.edu with misupport@kumc.edu
- Under "Questions?" at the bottom, replace the header and the text with the following:
I need help... what do I do?
·         Introduction to REDCap and HERON: Beginner Training Clinics Tuesdays 12pm-1pm CST. Click here to sign up. This is an introduction for new users or users needing a refresher
·         For questions or help with projects: REDCap & HERON Office Hours, Monday & Wednesday 4pm-5pm CST, Friday 9am-10am CST. Click here to sign up. This is not a beginner course; 15-20 min appointment to assist with specific questions
·         For support by email: Contact MI Support at misupport@kumc.edu
·         For project development by MI: Contact MI Support at misupport@kumc.edu Funding is required

- On the Select Team Members page, remove the broken Frontiers link and replace it with display text of "Medical Informatics" and the link https://www.kumc.edu/miea/medical-informatics.html. This was finally updated with the Frontier's latest website link instead of changing it to MI
- Needs to be updated on Sponsorship, Data Request, ACT Sponsorship, and GreenHERON requests Select Team pages (each is its own link)
-  Update the HERON Sponsorship Process with the following text, starting from "Only faculty…" and ending at the end of step 4.

Faculty members are automatically sponsored for HERON. Non-faculty researchers will need to have a sponsorship request submitted and approved by a faculty member.
Faculty member sponsoring non-faculty:
·         Click "HERON Sponsorship Request" under Regulatory Requests.
·         Enter the first / last name or username for sponsoree(s).
·         Select "done choosing people".
·         Complete the following form and click submit.

Non-faculty member requesting sponsorship:
·         Click "HERON Sponsorship Request" under Regulatory Requests.
·         Enter the first / last name or username for faculty sponsor and any other sponsorees.
·         Select "done choosing people".
·         Complete the following form and click submit.

- Update the HERON Data Request section with the following:
Remove step #1 under Data Request Process
Update step #2 (now step #1) to Click on "HERON Data Request" under Regulatory Requests.

- Rename "Request a Consultation" to "Office Hours" and replace the current link with https://redcap.kumc.edu/surveys/?s=3DHDJMKN4A

### CODE REVIEW

**Comment by nihr43** [comment]
instead of a generic "update website" commit message, can we give some brief indication to what changed?  for example, why did the id looking thing in line 48 of `heron_wsgi/templates/index.html` change?
this classic xkcd seems relevant: https://xkcd.com/1296/

**Comment by anuforok** [comment]
> instead of a generic "update website" commit message, can we give some brief indication to what changed? for example, why did the id looking thing in line 48 of `heron_wsgi/templates/index.html` change?
> this classic xkcd seems relevant: https://xkcd.com/1296/

Dear @nihr43 Thanks for the awesome feedback. My apologies on the commit message. I just used the title for the ticket. However I will update the description section of the commit as regards to notes from the meeting held for the changes. I believe using a brief indication for the commit change would have been off.

**Review by ari-raven-hall — COMMENTED** [review]
Incorrect links replaced with correct links. Looks good to me. - ARH

**Comment by nihr43** [comment]
the comments in github dont transfer to the git history.  commit messages are what are persisted in the history and are therefore what are viewable in git proper among other tools.

**Comment by anuforok** [comment]
> the comments in github dont transfer to the git history. commit messages are what are persisted in the history and are therefore what are viewable in git proper among other tools.

Dear @nihr43 thanks once again for the feedback. Henceforth I will endeavor to make sure each change is a separate commit with a brief indication of what the change is all about.

**Review by nihr43 — APPROVED** [review]

**Pull request merged**
