### PR TITLE
get tests working under Jenkins 2140

### PR DESCRIPTION
**Pull request by dckc**
[build 104](https://yellowfin:8443/job/heron-admin-test-build/104/) shows this working

### CODE REVIEW

**Comment by nihr43** [comment]
`ImportError: No module named injector`

I did:
```
pip install -r ./requirements.txt
./test/runtests.sh
```
injector seems to be present though:
```
Requirement already satisfied: injector==0.12.0
```

**Comment by dckc** [comment]
Where is `/usr/lib/python2.7`? How did you `pip install -r ./requirements.txt` into `/usr/lib` without root? Or are you root? Are you using a container?

The goal here is to run under Jenkins, though 2140 is about fragile tests and maybe they're still too fragile if they don't run easily in a container.

**Comment by nihr43** [comment]
I'm just doing so as `nhensel` on my laptop.
my packages are in `home/nhensel/.local/lib/python2.7/site-packages`

**Comment by nihr43** [comment]
also will you put `runtests.sh` through `shellcheck`?
theres a typo in the shebang

**Comment by nihr43** [comment]
I was eventually able to run this on my system.
I documented a few packages that were required for me to run it

**Pull request merged**
